#! /usr/bin/env php
<?php

include "vendor/autoload.php";

use Symfony\Component\Console\Application;
use VyalovAlexander\SumCommand;
$app = new Application("Welcome my friend.", "1.0.0");
$app->add(new SumCommand());
$app->run();
